import type { Metadata } from "next";
import { Noto_Sans_Hebrew, Secular_One } from "next/font/google";
import "./globals.css";
import ClientProviders from "./Providers/ClientProviders";
import Footer from "./components/Footer";

const noto = Noto_Sans_Hebrew({
  subsets: ["hebrew"],
  variable: "--font-noto",
});
const specular = Secular_One({
  subsets: ["hebrew"],
  variable: "--font-secular",
  weight: "400",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="he" dir="rtl">
      <ClientProviders>
          <body className={""}>
            {children}
            <Footer/>
            </body>
      </ClientProviders>
    </html>
  );
}
